name: Is Community User Check

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  check-is-community:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    env:
      SI_STAFF: "adamhjk AnnaAtMax britmyerss fnichol jhelwig mahirl nickgerace stack72 paulocsanz theoephraim vbustamante wendybujalski zacharyhamm"
    steps:
      - name: Checkout code
        id: check_author
        run: |
          PR_AUTHOR="${{ github.event.pull_request.user.login }}"
          if [[ $SI_STAFF =~ (^|[[:space:]])$PR_AUTHOR($|[[:space:]]) ]]; then
            echo "requires-community-tag=true" >> $GITHUB_OUTPUT
          else
            echo "Successfully checked the author against the staff list"
          fi
      - name: Label PR
        if: steps.check_author.outputs.requires-community-tag == 'true'
        uses: actions/github-script@v5
        with:
          script: |
            await github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: ${{ github.event.pull_request.number }},
              labels: ['community']
            });
